### ISSUE TITLE
Valgrind error in t8_gtest_cmesh_partition_parallel

### ISSUE THREAD

**Issue by lenaploetzke** [DLR-AMR/t8code#1922]
# Bug report

**Describe the bug**
Valgrind check for t8_gtest_cmesh_partition_parallel throws an error if valgrind is used with mpi.

**To Reproduce**
Change check_valgrind.sh script in line 69 to mpirun -n 3 valgrind $VALGRIND_FLAGS "${FILE}" > /dev/null 2>"${OUTPUT_FILE}" and run it with the file specified.

**Log files**
==2163846== Conditional jump or move depends on uninitialised value(s)
==2163846==    at 0x4B109B8: t8_cmesh_gather_treecount_ext(t8_cmesh*, int, int) (t8_cmesh_partition.cxx:209)
==2163846==    by 0x4B10AF3: t8_cmesh_gather_treecount_nocommit (t8_cmesh_partition.cxx:251)
==2163846==    by 0x4B14AAC: t8_cmesh_partition (t8_cmesh_partition.cxx:1588)
==2163846==    by 0x4B0FC87: t8_cmesh_commit (t8_cmesh_commit.cxx:582)
==2163846==    by 0x422B2D: t8_cmesh_partition_class_test_cmesh_partition_concentrate_Test::TestBody() (t8_gtest_cmesh_partition.cxx:136)
==2163846==    by 0x4D43DDA: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:4242)
==2163846==    by 0x4D3C61E: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:4278)
==2163846==    by 0x4D15D8F: testing::Test::Run() (gtest-all.cc:4317)
==2163846==    by 0x4D1672C: testing::TestInfo::Run() (gtest-all.cc:4496)
==2163846==    by 0x4D16F6A: testing::TestSuite::Run() (gtest-all.cc:4653)
==2163846==    by 0x4D23974: testing::internal::UnitTestImpl::RunAllTests() (gtest-all.cc:7432)
==2163846==    by 0x4D44C9B: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:4242)
==2163846==  Uninitialised value was created by a stack allocation

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04, Windows 11]
 - Compiler: [e.g., gcc, icc, mpicc]
 - Compiler version: [e.g. the output of 'gcc --version']
 - MPI version (if MPI is used): [The output of 'mpirun --version' or 'mpiexec --version']

**Estimated priority**
Which of these is most applicable (remove the others):

"Priority: high"  Should be solved as soon as possible

"Priority: medium"  Should be solved within half a year

"Priority: low" Should be solved eventually

**Additional context**

**Comment by holke** [comment]
It was kind of hard to pin down an individual test case where this fails, due to the vast number of test cases and the valgrind script unfortunately not printing our which test caused the valgrind error (would this even be possible?).

Here is one test that fails: test_cmesh_partition_concentrate/t8_cmesh_new_from_class_Vertex_sc_MPI_COMM_WORLD_default
I try to continue debugging.

**Comment by holke** [comment]
Done.
The issue was a non-initialized variable in t8_cmesh_uniform_bounds_from_unpartioned

**Comment by lenaploetzke** [comment]
Tbh i still get the same error (noticed while working on the parallel valgrind check in the ci). @holke can you check it again?

**Comment by holke** [comment]
Oh no,
will do!

Are you able to pin it down to a specific test case?

**Comment by lenaploetzke** [comment]
You can maybe use the changes in #1990, I hope this makes it easier to debug because the log files are not deleted at the end and the number of processes can be specified. No, I think it is not possible to print the specific test case.

**Comment by holke** [comment]
I ran it again with
`mpirun -np 3 valgrind --leak-check=full --track-origins=yes     --trace-children=yes --show-leak-kinds=definite,indirect,possible     --errors-for-leak-kinds=definite,indirect,possible ./test/t8_cmesh/t8_gtest_cmesh_partition_parallel` 

and did not find any error.

I have the log files on the team server but the file is too larg eto upload here.

**Comment by holke** [comment]
I could replicate it and hope i solved i now :)
